In [1]:
import pandas as pd
import numpy as n

In [2]:
df = pd.read_csv('C:/Users/ZMHD022/Desktop/HC/home-credit-default-risk/application_train.csv')

In [4]:
pd.crosstab(df['TARGET'], df['CODE_GENDER'])

CODE_GENDER       F      M  XNA
TARGET                         
0            188278  94404    4
1             14170  10655    0

In [7]:
pd.crosstab(df['TARGET'], df['FLAG_OWN_CAR'])

FLAG_OWN_CAR       N      Y
TARGET                     
0             185675  97011
1              17249   7576

In [11]:
own_car = pd.crosstab(df['TARGET'], df['FLAG_OWN_CAR'])
own_car

FLAG_OWN_CAR       N      Y
TARGET                     
0             185675  97011
1              17249   7576

In [12]:
stats.chi2_contingency(own_car)

(146.65601825576024,
 9.330994431109667e-34,
 1,
 array([[186542.18504054,  96143.81495946],
        [ 16381.81495946,   8443.18504054]]))

In [14]:
pd.crosstab(df['TARGET'], df['FLAG_OWN_REALTY'])

FLAG_OWN_REALTY      N       Y
TARGET                        
0                86357  196329
1                 7842   16983

In [15]:
own_house = pd.crosstab(df['TARGET'], df['FLAG_OWN_REALTY'])
own_house

FLAG_OWN_REALTY      N       Y
TARGET                        
0                86357  196329
1                 7842   16983

In [16]:
stats.chi2_contingency(own_house)

(11.575827298084178,
 0.0006681470317545887,
 1,
 array([[ 86594.42593598, 196091.57406402],
        [  7604.57406402,  17220.42593598]]))

In [17]:
no_child = pd.crosstab(df['TARGET'],df['CNT_CHILDREN'])
no_child

CNT_CHILDREN      0      1      2     3    4   5   6   7   8   9   10  11  12  \
TARGET                                                                          
0             198762  55665  24416  3359  374  77  15   7   2   0   2   0   2   
1              16609   5454   2333   358   55   7   6   0   0   2   0   1   0   

CNT_CHILDREN  14  19  
TARGET                
0              3   2  
1              0   0

In [18]:
stats.chi2_contingency(no_child)

(185.4517870533278,
 5.061088526096429e-32,
 14,
 array([[1.97984353e+05, 5.61849353e+04, 2.45895848e+04, 3.41693098e+03,
         3.94367336e+02, 7.72187792e+01, 1.93046948e+01, 6.43489826e+00,
         1.83854236e+00, 1.83854236e+00, 1.83854236e+00, 9.19271181e-01,
         1.83854236e+00, 2.75781354e+00, 1.83854236e+00],
        [1.73866466e+04, 4.93406472e+03, 2.15941519e+03, 3.00069022e+02,
         3.46326635e+01, 6.78122083e+00, 1.69530521e+00, 5.65101736e-01,
         1.61457639e-01, 1.61457639e-01, 1.61457639e-01, 8.07288195e-02,
         1.61457639e-01, 2.42186458e-01, 1.61457639e-01]]))

In [19]:
accompyning = pd.crosstab(df['TARGET'], df['NAME_TYPE_SUITE'])
accompyning

NAME_TYPE_SUITE  Children  Family  Group of people  Other_A  Other_B  \
TARGET                                                                 
0                    3026   37140              248      790     1596   
1                     241    3009               23       76      174   

NAME_TYPE_SUITE  Spouse, partner  Unaccompanied  
TARGET                                           
0                          10475         228189  
1                            895          20337

In [20]:
stats.chi2_contingency(accompyning)

(32.825314655829914,
 1.1329313903575907e-05,
 6,
 array([[3.00289299e+03, 3.69033213e+04, 2.49092133e+02, 7.95991836e+02,
         1.62691172e+03, 1.04508397e+04, 2.28434950e+05],
        [2.64107012e+02, 3.24567873e+03, 2.19078666e+01, 7.00081641e+01,
         1.43088280e+02, 9.19160307e+02, 2.00910496e+04]]))

In [22]:
income_type = pd.crosstab(df['TARGET'], df['NAME_INCOME_TYPE'])
income_type

NAME_INCOME_TYPE  Businessman  Commercial associate  Maternity leave  \
TARGET                                                                 
0                          10                 66257                3   
1                           0                  5360                2   

NAME_INCOME_TYPE  Pensioner  State servant  Student  Unemployed  Working  
TARGET                                                                    
0                     52380          20454       18          14   143550  
1                      2982           1249        0           8    15224

In [23]:
stats.chi2_contingency(income_type)

(1253.4708080924988,
 1.9281456056858933e-266,
 7,
 array([[9.19271181e+00, 6.58354441e+04, 4.59635590e+00, 5.08926911e+04,
         1.99509424e+04, 1.65468812e+01, 2.02239660e+01, 1.45956362e+05],
        [8.07288195e-01, 5.78155586e+03, 4.03644097e-01, 4.46930890e+03,
         1.75205757e+03, 1.45311875e+00, 1.77603403e+00, 1.28176376e+04]]))

In [24]:
edu_type = pd.crosstab(df['TARGET'], df['NAME_EDUCATION_TYPE'])
edu_type

NAME_EDUCATION_TYPE  Academic degree  Higher education  Incomplete higher  \
TARGET                                                                      
0                                161             70854               9405   
1                                  3              4009                872   

NAME_EDUCATION_TYPE  Lower secondary  Secondary / secondary special  
TARGET                                                               
0                               3399                         198867  
1                                417                          19524

In [25]:
stats.chi2_contingency(edu_type)

(1019.2131873088356,
 2.4476812052198174e-219,
 4,
 array([[1.50760474e+02, 6.88193984e+04, 9.44734992e+03, 3.50793882e+03,
         2.00760552e+05],
        [1.32395264e+01, 6.04360161e+03, 8.29650078e+02, 3.08061175e+02,
         1.76304476e+04]]))

In [26]:
family_status = pd.crosstab(df['TARGET'], df['NAME_FAMILY_STATUS'])
family_status

NAME_FAMILY_STATUS  Civil marriage  Married  Separated  Single / not married  \
TARGET                                                                         
0                            26814   181582      18150                 40987   
1                             2961    14850       1620                  4457   

NAME_FAMILY_STATUS  Unknown  Widow  
TARGET                              
0                         2  15151  
1                         0    937

In [27]:
stats.chi2_contingency(family_status)

(504.69408255632106,
 7.744841561414258e-107,
 5,
 array([[2.73712994e+04, 1.80574277e+05, 1.81739912e+04, 4.17753595e+04,
         1.83854236e+00, 1.47892348e+04],
        [2.40370060e+03, 1.58577235e+04, 1.59600876e+03, 3.66864047e+03,
         1.61457639e-01, 1.29876525e+03]]))

In [28]:
housing_type = pd.crosstab(df['TARGET'], df['NAME_HOUSING_TYPE'])
housing_type

NAME_HOUSING_TYPE  Co-op apartment  House / apartment  Municipal apartment  \
TARGET                                                                       
0                             1033             251596                10228   
1                               89              21272                  955   

NAME_HOUSING_TYPE  Office apartment  Rented apartment  With parents  
TARGET                                                               
0                              2445              4280         13104  
1                               172               601          1736

In [29]:
stats.chi2_contingency(housing_type)

(420.55618983894664,
 1.0990890032617707e-88,
 5,
 array([[1.03142226e+03, 2.50839688e+05, 1.02802096e+04, 2.40573268e+03,
         4.48696263e+03, 1.36419843e+04],
        [9.05777354e+01, 2.20283115e+04, 9.02790388e+02, 2.11267321e+02,
         3.94037368e+02, 1.19801568e+03]]))

In [30]:
house = pd.crosstab(df['FLAG_OWN_REALTY'], df['NAME_HOUSING_TYPE'])
house

NAME_HOUSING_TYPE  Co-op apartment  House / apartment  Municipal apartment  \
FLAG_OWN_REALTY                                                              
N                              424              73671                 6822   
Y                              698             199197                 4361   

NAME_HOUSING_TYPE  Office apartment  Rented apartment  With parents  
FLAG_OWN_REALTY                                                      
N                              1224              2795          9263  
Y                              1393              2086          5577

In [31]:
stats.chi2_contingency(house)

(15583.14370290803,
 0.0,
 5,
 array([[   343.69917824,  83586.90496275,   3425.65767403,
            801.65842198,   1495.18332352,   4545.89643948],
        [   778.30082176, 189281.09503725,   7757.34232597,
           1815.34157802,   3385.81667648,  10294.10356052]]))

In [32]:
car_age = pd.crosstab(df['TARGET'], df['OWN_CAR_AGE'])
car_age

OWN_CAR_AGE  0.0   1.0   2.0   3.0   4.0   5.0   6.0   7.0   8.0   9.0   ...  \
TARGET                                                                   ...   
0            1987  4944  5501  6052  5257  3409  6026  6991  5516  4666  ...   
1             147   336   351   318   300   186   356   433   371   354  ...   

OWN_CAR_AGE  52.0  54.0  55.0  56.0  57.0  63.0  64.0  65.0  69.0  91.0  
TARGET                                                                   
0               1    12     4     1     0     2  2233   822     1     1  
1               0     0     0     0     1     0   210    69     0     1  

[2 rows x 62 columns]

In [33]:
stats.chi2_contingency(car_age)

(423.99249836832115,
 8.695299944334695e-56,
 61,
 array([[1.97941141e+03, 4.89751277e+03, 5.42807665e+03, 5.90855233e+03,
         5.15444667e+03, 3.33457545e+03, 5.91968304e+03, 6.88619977e+03,
         5.46054122e+03, 4.65634736e+03, 4.45784969e+03, 3.85957398e+03,
         3.94861967e+03, 4.23523547e+03, 4.26120713e+03, 3.32066206e+03,
         3.11196124e+03, 2.68899422e+03, 2.24283823e+03, 1.72897042e+03,
         1.41638295e+03, 1.35609160e+03, 1.15944904e+03, 9.89705705e+02,
         1.06669312e+03, 8.02338739e+02, 5.37984357e+02, 4.48011111e+02,
         5.02737106e+02, 3.68241017e+02, 3.02384311e+02, 2.47658316e+02,
         1.92932321e+02, 1.22437819e+02, 1.69743340e+02, 1.45626800e+02,
         1.15017345e+02, 6.95669427e+01, 8.99732459e+01, 7.23496204e+01,
         7.88425350e+01, 5.37984357e+01, 3.89574879e+01, 1.76236255e+01,
         1.94787440e+01, 1.02031516e+01, 4.63779618e+00, 9.27559236e-01,
         9.27559236e-01, 5.56535541e+00, 9.27559236e-01, 2.78267771e+00,
 

In [34]:
mobno_given = pd.crosstab(df['TARGET'], df['FLAG_MOBIL'])
mobno_given

FLAG_MOBIL  0       1
TARGET               
0           1  282685
1           0   24825

In [35]:
stats.chi2_contingency(mobno_given)

(2.3687497870672676,
 0.12378615154489818,
 1,
 array([[9.19271181e-01, 2.82685081e+05],
        [8.07288195e-02, 2.48249193e+04]]))

In [36]:
wkphno_given = pd.crosstab(df['TARGET'], df['FLAG_EMP_PHONE'])
wkphno_given

FLAG_EMP_PHONE      0       1
TARGET                       
0               52395  230291
1                2991   21834

In [37]:
stats.chi2_contingency(wkphno_given)

(649.7511805111201,
 2.530605927961308e-143,
 1,
 array([[ 50914.75360556, 231771.24639444],
        [  4471.24639444,  20353.75360556]]))

In [38]:
hmphno_given = pd.crosstab(df['TARGET'], df['FLAG_WORK_PHONE'])
hmphno_given

FLAG_WORK_PHONE       0      1
TARGET                        
0                227282  55404
1                 18921   5904

In [39]:
stats.chi2_contingency(hmphno_given)

(249.94030531993508,
 2.6758000919452704e-56,
 1,
 array([[226327.32246326,  56358.67753674],
        [ 19875.67753674,   4949.32246326]]))

In [40]:
mob_reach= pd.crosstab(df['TARGET'], df['FLAG_CONT_MOBILE'])
mob_reach

FLAG_CONT_MOBILE    0       1
TARGET                       
0                 529  282157
1                  45   24780

In [41]:
stats.chi2_contingency(mob_reach)

(0.016529895300634423,
 0.8976989816319643,
 1,
 array([[5.27661658e+02, 2.82158338e+05],
        [4.63383424e+01, 2.47786617e+04]]))

In [42]:
mob_given_reach= pd.crosstab(df['FLAG_MOBIL'], df['FLAG_CONT_MOBILE'])
mob_given_reach

FLAG_CONT_MOBILE    0       1
FLAG_MOBIL                   
0                   0       1
1                 574  306936

In [43]:
stats.chi2_contingency(mob_given_reach)

(133.1842629960505,
 8.239797898091087e-31,
 1,
 array([[1.86659989e-03, 9.98133400e-01],
        [5.73998133e+02, 3.06936002e+05]]))

In [44]:
same_clm= pd.crosstab(df['FLAG_WORK_PHONE'], df['FLAG_PHONE'])
same_clm

FLAG_PHONE            0      1
FLAG_WORK_PHONE               
0                193191  53012
1                 27889  33419

In [46]:
stats.chi2_contingency(same_clm)

(26416.723088156643, 0.0, 1, array([[177003.61691126,  69199.38308874],
        [ 44076.38308874,  17231.61691126]]))

In [47]:
email_given= pd.crosstab(df['TARGET'], df['FLAG_EMAIL'])
email_given

FLAG_EMAIL       0      1
TARGET                   
0           266618  16068
1            23451   1374

In [48]:
stats.chi2_contingency(email_given)

(0.92309632556523,
 0.3366632895181666,
 1,
 array([[266652.07206897,  16033.92793103],
        [ 23416.92793103,   1408.07206897]]))

In [49]:
occup_type=pd.crosstab(df['TARGET'],df['OCCUPATION_TYPE'])
occup_type

OCCUPATION_TYPE  Accountants  Cleaning staff  Cooking staff  Core staff  \
TARGET                                                                    
0                       9339            4206           5325       25832   
1                        474             447            621        1738   

OCCUPATION_TYPE  Drivers  HR staff  High skill tech staff  IT staff  Laborers  \
TARGET                                                                          
0                  16496       527                  10679       492     49348   
1                   2107        36                    701        34      5838   

OCCUPATION_TYPE  Low-skill Laborers  Managers  Medicine staff  \
TARGET                                                          
0                              1734     20043            7965   
1                               359      1328             572   

OCCUPATION_TYPE  Private service staff  Realty agents  Sales staff  \
TARGET                                                               
0                                 2477            692        29010   
1                                  175             59         3092   

OCCUPATION_TYPE  Secretaries  Security staff  Waiters/barmen staff  
TARGET                                                              
0                       1213            5999                  1196  
1                         92             722                   152

In [50]:
stats.chi2_contingency(occup_type)

(1402.8467961927513,
 3.784499856764699e-288,
 17,
 array([[8.95092293e+03, 4.24423157e+03, 5.42364086e+03, 2.51479614e+04,
         1.69687169e+04, 5.13540162e+02, 1.03802612e+04, 4.79790631e+02,
         5.03378817e+04, 1.90912888e+03, 1.94935467e+04, 7.78702018e+03,
         2.41902044e+03, 6.85024266e+02, 2.92818229e+04, 1.19035508e+03,
         6.13055671e+03, 1.22957751e+03],
        [8.62077070e+02, 4.08768430e+02, 5.22359142e+02, 2.42203860e+03,
         1.63428307e+03, 4.94598380e+01, 9.99738822e+02, 4.62093691e+01,
         4.84811833e+03, 1.83871121e+02, 1.87745328e+03, 7.49979817e+02,
         2.32979557e+02, 6.59757342e+01, 2.82017712e+03, 1.14644918e+02,
         5.90443288e+02, 1.18422490e+02]]))

In [52]:
family_numb=pd.crosstab(df['TARGET'],df['CNT_FAM_MEMBERS'])
family_numb


CNT_FAM_MEMBERS   1.0     2.0    3.0    4.0   5.0   6.0   7.0   8.0   9.0   \
TARGET                                                                       
0                62172  146348  47993  22561  3151   353    75    14     6   
1                 5675   12009   4608   2136   327    55     6     6     0   

CNT_FAM_MEMBERS  10.0  11.0  12.0  13.0  14.0  15.0  16.0  20.0  
TARGET                                                           
0                   2     0     2     0     2     1     2     2  
1                   1     1     0     1     0     0     0     0

In [53]:
stats.chi2_contingency(family_numb)

(167.4373228270056,
 2.730183369578879e-27,
 16,
 array([[6.23697562e+04, 1.45572943e+05, 4.83545557e+04, 2.27032274e+04,
         3.19722334e+03, 3.75062427e+02, 7.44609231e+01, 1.83854131e+01,
         5.51562393e+00, 2.75781197e+00, 9.19270655e-01, 1.83854131e+00,
         9.19270655e-01, 1.83854131e+00, 9.19270655e-01, 1.83854131e+00,
         1.83854131e+00],
        [5.47724384e+03, 1.27840568e+04, 4.24644425e+03, 1.99377262e+03,
         2.80776660e+02, 3.29375726e+01, 6.53907691e+00, 1.61458689e+00,
         4.84376067e-01, 2.42188034e-01, 8.07293445e-02, 1.61458689e-01,
         8.07293445e-02, 1.61458689e-01, 8.07293445e-02, 1.61458689e-01,
         1.61458689e-01]]))

In [6]:
df.corr()

SK_ID_CURR    TARGET  CNT_CHILDREN  \
SK_ID_CURR                     1.000000 -0.002108     -0.001129   
TARGET                        -0.002108  1.000000      0.019187   
CNT_CHILDREN                  -0.001129  0.019187      1.000000   
AMT_INCOME_TOTAL              -0.001820 -0.003982      0.012882   
AMT_CREDIT                    -0.000343 -0.030369      0.002145   
AMT_ANNUITY                   -0.000433 -0.012817      0.021374   
AMT_GOODS_PRICE               -0.000232 -0.039645     -0.001827   
REGION_POPULATION_RELATIVE     0.000849 -0.037227     -0.025573   
DAYS_BIRTH                    -0.001500  0.078239      0.330938   
DAYS_EMPLOYED                  0.001366 -0.044932     -0.239818   
DAYS_REGISTRATION             -0.000973  0.041975      0.183395   
DAYS_ID_PUBLISH               -0.000384  0.051457     -0.028019   
OWN_CAR_AGE                    0.001818  0.037612      0.008494   
FLAG_MOBIL                     0.002804  0.000534      0.001041   
FLAG_EMP_PHONE                -0.001337  0.045982      0.240714   
FLAG_WORK_PHONE               -0.000415  0.028524      0.055630   
FLAG_CONT_MOBILE               0.002815  0.000370     -0.000794   
FLAG_PHONE                     0.002753 -0.023806     -0.029906   
FLAG_EMAIL                     0.000281 -0.001758      0.022619   
CNT_FAM_MEMBERS               -0.002895  0.009308      0.879161   
REGION_RATING_CLIENT          -0.001075  0.058899      0.025423   
REGION_RATING_CLIENT_W_CITY   -0.001138  0.060893      0.024781   
HOUR_APPR_PROCESS_START        0.000350 -0.024166     -0.007292   
REG_REGION_NOT_LIVE_REGION    -0.000283  0.005576     -0.013319   
REG_REGION_NOT_WORK_REGION     0.001097  0.006942      0.008185   
LIVE_REGION_NOT_WORK_REGION    0.002903  0.002819      0.014835   
REG_CITY_NOT_LIVE_CITY        -0.001885  0.044395      0.020072   
REG_CITY_NOT_WORK_CITY        -0.001582  0.050994      0.070650   
LIVE_CITY_NOT_WORK_CITY        0.000067  0.032518      0.069957   
EXT_SOURCE_1                   0.000082 -0.155317     -0.138470   
...                                 ...       ...           ...   
DEF_30_CNT_SOCIAL_CIRCLE      -0.000082  0.032248     -0.001262   
OBS_60_CNT_SOCIAL_CIRCLE      -0.001423  0.009022      0.015232   
DEF_60_CNT_SOCIAL_CIRCLE       0.001187  0.031276     -0.001861   
DAYS_LAST_PHONE_CHANGE        -0.000858  0.055218     -0.005865   
FLAG_DOCUMENT_2                0.000700  0.005417      0.001786   
FLAG_DOCUMENT_3               -0.003411  0.044346      0.056837   
FLAG_DOCUMENT_4               -0.004139 -0.002672     -0.003709   
FLAG_DOCUMENT_5               -0.001097 -0.000316     -0.016737   
FLAG_DOCUMENT_6                0.002121 -0.028602     -0.157024   
FLAG_DOCUMENT_7               -0.002694 -0.001520     -0.001498   
FLAG_DOCUMENT_8                0.001809 -0.008040      0.051697   
FLAG_DOCUMENT_9                0.001505 -0.004352     -0.001997   
FLAG_DOCUMENT_10              -0.000815 -0.001414     -0.002756   
FLAG_DOCUMENT_11              -0.002012 -0.004229     -0.005318   
FLAG_DOCUMENT_12              -0.001045 -0.000756      0.000293   
FLAG_DOCUMENT_13               0.000896 -0.011583      0.003945   
FLAG_DOCUMENT_14              -0.001077 -0.009464     -0.005459   
FLAG_DOCUMENT_15               0.002604 -0.006536      0.003609   
FLAG_DOCUMENT_16              -0.000724 -0.011615      0.010662   
FLAG_DOCUMENT_17               0.001450 -0.003378      0.000773   
FLAG_DOCUMENT_18               0.000509 -0.007952      0.004031   
FLAG_DOCUMENT_19               0.000167 -0.001358      0.000864   
FLAG_DOCUMENT_20               0.001073  0.000215      0.000988   
FLAG_DOCUMENT_21               0.000282  0.003709     -0.002450   
AMT_REQ_CREDIT_BUREAU_HOUR    -0.002672  0.000930     -0.000410   
AMT_REQ_CREDIT_BUREAU_DAY     -0.002193  0.002704     -0.000366   
AMT_REQ_CREDIT_BUREAU_WEEK     0.002099  0.000788     -0.002436   
AMT_REQ_CREDIT_BUREAU_MON      0.000485 -0.012462     -0.010808   
AMT_REQ_C

In [ ]:
family_numb=pd.crosstab(df['TARGET'],df[''])
family_numb